- name: Deploy Nagios Templates
  hosts: nagios_server
  become: yes
  gather_facts: no

  tasks:
    - name: Gather host information
      setup:
        filter: ansible_all_ipv4_addresses

    - name: Create Nagios config directory
      file:
        path: /etc/nagios/conf.d
        state: directory

    - name: Generate Nagios config files
      template:
        src: nagios_host.j2
        dest: /etc/nagios/conf.d/{{ inventory_hostname }}.cfg
      with_items: "{{ groups['hosts'] }}"
      loop_control:
        loop_var: host

      vars:
        nagios_server_address: "{{ ansible_default_ipv4.address }}"

  handlers:
    - name: Restart Nagios
      service:
        name: nagios
        state: restarted
