version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - nginx_logs:/var/log/nginx
    networks:
      - custom_bridge
    depends_on:
      - custom_bridge

networks:
  custom_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.8.0/24

volumes:
  nginx_logs:


